#-----dnsmasq.conf — Configuración de DHCP y TFTP-----#
#
# dnsmasq se encarga de:
#   1. DHCP: reparte IPs a los equipos que arrancan por PXE
#   2. TFTP: sirve los ficheros de arranque (kernels, menús)


#-----Interfaz de red-----
# Indicamos en que interfaz escuchrá dnsmasq
interface=eth0
bind-interfaces
except-interface=lo   # Ignoramos la interfaz de loopback (127.0.0.1)


#-----DNS local-----
# Configuramos un dominio local pxe.local
# para que los equipos puedan resolverse entre ellos.
domain=pxe.local
local=/pxe.local/


#-----DHCP-----
# Rango de IPs que repartiremos a los clientes.
# Formato: IP_inicio, IP_fin, máscara, tiempo de concesión
dhcp-range=192.168.100.50,192.168.100.200,255.255.255.0,12h

# Indicamos a los clientes que la puerta de enlace y el DNS es la propia RPi
dhcp-option=3,192.168.100.1   # Gateway
dhcp-option=6,192.168.100.1   # DNS

# Con esto dnsmasq es el servidor DHCP autoritativo,
# el único que reparte IPs en esta red
dhcp-authoritative


#-----TFTP-----
# Activamos el servidor TFTP y le decimos dónde
# están los ficheros que va a servir
enable-tftp
tftp-root=/tftpboot


#-----PXE para equipos con BIOS clásica-----
# Cuando un equipo con BIOS pide arrancar por red,
# le mandamos el fichero pxelinux.0
dhcp-boot=pxelinux.0,pxeserver,192.168.100.1


#-----PXE para equipos con UEFI-----
# Los equipos modernos con UEFI usan un fichero diferente.
# Detectamos si el cliente es UEFI y le mandamos grubx64.efi
dhcp-match=set:efi-x86_64,option:client-arch,7
dhcp-boot=tag:efi-x86_64,grubx64.efi,pxeserver,192.168.100.1


#-----Logs-----
# Activamos logs del DHCP para ver qué equipos están pidiendo IP
log-dhcp
